#I created this to find all of the hayabusa offline events generated by RTW, copy/rename them with a unique name to a single dir for concatenation and import into SOF-ELK
# Set the Case Name variable, then define the directory to search in; for RTW this is "kape_output"
$casename = '2025-7-1234ir'
$sourceDirectory = "D:\cases\$casename\kape_output"

# Define the file name to search for; for RTW this is "hayabusa_events_offline.csv"
$fileName = "hayabusa_events_offline.csv"

# Define the destination directory for all of the csv's
$destinationDirectory = "D:\cases\$casename\hayabusa-events-offline"
New-Item -path $destinationDirectory -ItemType Directory

# Recursively search for the file in your source dir
$files = Get-ChildItem -Path $sourceDirectory -Recurse -Filter $fileName

# Copy and rename the file with a unique name; date-time-milliseconds, as below
foreach ($file in $files) {
    # Generate a unique name using a timestamp
    $uniqueName = "hayabusa_" + (Get-Date -Format "yyyyMMddHHmmssfff") + ".csv"
    $destinationPath = Join-Path -Path $destinationDirectory -ChildPath $uniqueName
    Copy-Item -Path $file.FullName -Destination $destinationPath
    Write-Output "Copied and renamed $($file.FullName) to $destinationPath"
}
